/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicCheckoutRouteImport } from './routes/api/public/checkout'
import { Route as ApiPublicCollectionsRouteImport } from './routes/api/public/collections'
import { Route as ApiPublicProductsRouteImport } from './routes/api/public/products'
import { Route as ApiPublicPaymentsVerifyRouteImport } from './routes/api/public/payments.verify'
import { Route as ApiPublicProductsSlugRouteImport } from './routes/api/public/products.$slug'
import { Route as ApiPublicWebhooksRazorpayRouteImport } from './routes/api/public/webhooks.razorpay'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCheckoutRoute = ApiPublicCheckoutRouteImport.update({
  id: '/api/public/checkout',
  path: '/api/public/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCollectionsRoute = ApiPublicCollectionsRouteImport.update({
  id: '/api/public/collections',
  path: '/api/public/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProductsRoute = ApiPublicProductsRouteImport.update({
  id: '/api/public/products',
  path: '/api/public/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsVerifyRoute = ApiPublicPaymentsVerifyRouteImport.update({
  id: '/api/public/payments/verify',
  path: '/api/public/payments/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProductsSlugRoute = ApiPublicProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiPublicProductsRoute,
} as any)
const ApiPublicWebhooksRazorpayRoute =
  ApiPublicWebhooksRazorpayRouteImport.update({
    id: '/api/public/webhooks/razorpay',
    path: '/api/public/webhooks/razorpay',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/checkout': typeof ApiPublicCheckoutRoute
  '/api/public/collections': typeof ApiPublicCollectionsRoute
  '/api/public/products': typeof ApiPublicProductsRouteWithChildren
  '/api/public/payments/verify': typeof ApiPublicPaymentsVerifyRoute
  '/api/public/products/$slug': typeof ApiPublicProductsSlugRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/checkout': typeof ApiPublicCheckoutRoute
  '/api/public/collections': typeof ApiPublicCollectionsRoute
  '/api/public/products': typeof ApiPublicProductsRouteWithChildren
  '/api/public/payments/verify': typeof ApiPublicPaymentsVerifyRoute
  '/api/public/products/$slug': typeof ApiPublicProductsSlugRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/checkout': typeof ApiPublicCheckoutRoute
  '/api/public/collections': typeof ApiPublicCollectionsRoute
  '/api/public/products': typeof ApiPublicProductsRouteWithChildren
  '/api/public/payments/verify': typeof ApiPublicPaymentsVerifyRoute
  '/api/public/products/$slug': typeof ApiPublicProductsSlugRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/checkout'
    | '/api/public/collections'
    | '/api/public/products'
    | '/api/public/payments/verify'
    | '/api/public/products/$slug'
    | '/api/public/webhooks/razorpay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/checkout'
    | '/api/public/collections'
    | '/api/public/products'
    | '/api/public/payments/verify'
    | '/api/public/products/$slug'
    | '/api/public/webhooks/razorpay'
  id:
    | '__root__'
    | '/'
    | '/api/public/checkout'
    | '/api/public/collections'
    | '/api/public/products'
    | '/api/public/payments/verify'
    | '/api/public/products/$slug'
    | '/api/public/webhooks/razorpay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicCheckoutRoute: typeof ApiPublicCheckoutRoute
  ApiPublicCollectionsRoute: typeof ApiPublicCollectionsRoute
  ApiPublicProductsRoute: typeof ApiPublicProductsRouteWithChildren
  ApiPublicPaymentsVerifyRoute: typeof ApiPublicPaymentsVerifyRoute
  ApiPublicWebhooksRazorpayRoute: typeof ApiPublicWebhooksRazorpayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/checkout': {
      id: '/api/public/checkout'
      path: '/api/public/checkout'
      fullPath: '/api/public/checkout'
      preLoaderRoute: typeof ApiPublicCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/collections': {
      id: '/api/public/collections'
      path: '/api/public/collections'
      fullPath: '/api/public/collections'
      preLoaderRoute: typeof ApiPublicCollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/products': {
      id: '/api/public/products'
      path: '/api/public/products'
      fullPath: '/api/public/products'
      preLoaderRoute: typeof ApiPublicProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/verify': {
      id: '/api/public/payments/verify'
      path: '/api/public/payments/verify'
      fullPath: '/api/public/payments/verify'
      preLoaderRoute: typeof ApiPublicPaymentsVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/products/$slug': {
      id: '/api/public/products/$slug'
      path: '/$slug'
      fullPath: '/api/public/products/$slug'
      preLoaderRoute: typeof ApiPublicProductsSlugRouteImport
      parentRoute: typeof ApiPublicProductsRoute
    }
    '/api/public/webhooks/razorpay': {
      id: '/api/public/webhooks/razorpay'
      path: '/api/public/webhooks/razorpay'
      fullPath: '/api/public/webhooks/razorpay'
      preLoaderRoute: typeof ApiPublicWebhooksRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiPublicProductsRouteChildren {
  ApiPublicProductsSlugRoute: typeof ApiPublicProductsSlugRoute
}

const ApiPublicProductsRouteChildren: ApiPublicProductsRouteChildren = {
  ApiPublicProductsSlugRoute: ApiPublicProductsSlugRoute,
}

const ApiPublicProductsRouteWithChildren =
  ApiPublicProductsRoute._addFileChildren(ApiPublicProductsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicCheckoutRoute: ApiPublicCheckoutRoute,
  ApiPublicCollectionsRoute: ApiPublicCollectionsRoute,
  ApiPublicProductsRoute: ApiPublicProductsRouteWithChildren,
  ApiPublicPaymentsVerifyRoute: ApiPublicPaymentsVerifyRoute,
  ApiPublicWebhooksRazorpayRoute: ApiPublicWebhooksRazorpayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
