/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAuditLogsRouteImport } from './routes/admin/audit-logs'
import { Route as AdminCollectionsRouteImport } from './routes/admin/collections'
import { Route as AdminCouponsRouteImport } from './routes/admin/coupons'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminImportRouteImport } from './routes/admin/import'
import { Route as AdminInventoryRouteImport } from './routes/admin/inventory'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminStaffIndexRouteImport } from './routes/admin/staff/index'
import { Route as AdminStaffStaffIdRouteImport } from './routes/admin/staff/$staffId'
import { Route as AdminStaffPermissionsRouteImport } from './routes/admin/staff/permissions'
import { Route as ApiPublicCheckoutRouteImport } from './routes/api/public/checkout'
import { Route as ApiPublicCollectionsRouteImport } from './routes/api/public/collections'
import { Route as ApiPublicProductsRouteImport } from './routes/api/public/products'
import { Route as ApiPublicPaymentsVerifyRouteImport } from './routes/api/public/payments.verify'
import { Route as ApiPublicProductsSlugRouteImport } from './routes/api/public/products.$slug'
import { Route as ApiPublicShippingQuoteRouteImport } from './routes/api/public/shipping.quote'
import { Route as ApiPublicWebhooksRazorpayRouteImport } from './routes/api/public/webhooks.razorpay'
import { Route as ApiPublicWebhooksShiprocketRouteImport } from './routes/api/public/webhooks.shiprocket'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/audit-logs',
  path: '/audit-logs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCollectionsRoute = AdminCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminImportRoute = AdminImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStaffIndexRoute = AdminStaffIndexRouteImport.update({
  id: '/staff/',
  path: '/staff/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStaffStaffIdRoute = AdminStaffStaffIdRouteImport.update({
  id: '/staff/$staffId',
  path: '/staff/$staffId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminStaffPermissionsRoute = AdminStaffPermissionsRouteImport.update({
  id: '/staff/permissions',
  path: '/staff/permissions',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ApiPublicCheckoutRoute = ApiPublicCheckoutRouteImport.update({
  id: '/api/public/checkout',
  path: '/api/public/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCollectionsRoute = ApiPublicCollectionsRouteImport.update({
  id: '/api/public/collections',
  path: '/api/public/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProductsRoute = ApiPublicProductsRouteImport.update({
  id: '/api/public/products',
  path: '/api/public/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsVerifyRoute = ApiPublicPaymentsVerifyRouteImport.update({
  id: '/api/public/payments/verify',
  path: '/api/public/payments/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProductsSlugRoute = ApiPublicProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiPublicProductsRoute,
} as any)
const ApiPublicShippingQuoteRoute = ApiPublicShippingQuoteRouteImport.update({
  id: '/api/public/shipping/quote',
  path: '/api/public/shipping/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksRazorpayRoute =
  ApiPublicWebhooksRazorpayRouteImport.update({
    id: '/api/public/webhooks/razorpay',
    path: '/api/public/webhooks/razorpay',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksShiprocketRoute =
  ApiPublicWebhooksShiprocketRouteImport.update({
    id: '/api/public/webhooks/shiprocket',
    path: '/api/public/webhooks/shiprocket',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/staff/$staffId': typeof AdminStaffStaffIdRoute
  '/admin/staff/permissions': typeof AdminStaffPermissionsRoute
  '/api/public/checkout': typeof ApiPublicCheckoutRoute
  '/api/public/collections': typeof ApiPublicCollectionsRoute
  '/api/public/products': typeof ApiPublicProductsRouteWithChildren
  '/admin/staff/': typeof AdminStaffIndexRoute
  '/api/public/payments/verify': typeof ApiPublicPaymentsVerifyRoute
  '/api/public/products/$slug': typeof ApiPublicProductsSlugRoute
  '/api/public/shipping/quote': typeof ApiPublicShippingQuoteRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
  '/api/public/webhooks/shiprocket': typeof ApiPublicWebhooksShiprocketRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin': typeof AdminIndexRoute
  '/admin/staff/$staffId': typeof AdminStaffStaffIdRoute
  '/admin/staff/permissions': typeof AdminStaffPermissionsRoute
  '/api/public/checkout': typeof ApiPublicCheckoutRoute
  '/api/public/collections': typeof ApiPublicCollectionsRoute
  '/api/public/products': typeof ApiPublicProductsRouteWithChildren
  '/admin/staff': typeof AdminStaffIndexRoute
  '/api/public/payments/verify': typeof ApiPublicPaymentsVerifyRoute
  '/api/public/products/$slug': typeof ApiPublicProductsSlugRoute
  '/api/public/shipping/quote': typeof ApiPublicShippingQuoteRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
  '/api/public/webhooks/shiprocket': typeof ApiPublicWebhooksShiprocketRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/import': typeof AdminImportRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/staff/$staffId': typeof AdminStaffStaffIdRoute
  '/admin/staff/permissions': typeof AdminStaffPermissionsRoute
  '/api/public/checkout': typeof ApiPublicCheckoutRoute
  '/api/public/collections': typeof ApiPublicCollectionsRoute
  '/api/public/products': typeof ApiPublicProductsRouteWithChildren
  '/admin/staff/': typeof AdminStaffIndexRoute
  '/api/public/payments/verify': typeof ApiPublicPaymentsVerifyRoute
  '/api/public/products/$slug': typeof ApiPublicProductsSlugRoute
  '/api/public/shipping/quote': typeof ApiPublicShippingQuoteRoute
  '/api/public/webhooks/razorpay': typeof ApiPublicWebhooksRazorpayRoute
  '/api/public/webhooks/shiprocket': typeof ApiPublicWebhooksShiprocketRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/audit-logs'
    | '/admin/collections'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/import'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/'
    | '/admin/staff/$staffId'
    | '/admin/staff/permissions'
    | '/api/public/checkout'
    | '/api/public/collections'
    | '/api/public/products'
    | '/admin/staff/'
    | '/api/public/payments/verify'
    | '/api/public/products/$slug'
    | '/api/public/shipping/quote'
    | '/api/public/webhooks/razorpay'
    | '/api/public/webhooks/shiprocket'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/audit-logs'
    | '/admin/collections'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/import'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/admin'
    | '/admin/staff/$staffId'
    | '/admin/staff/permissions'
    | '/api/public/checkout'
    | '/api/public/collections'
    | '/api/public/products'
    | '/admin/staff'
    | '/api/public/payments/verify'
    | '/api/public/products/$slug'
    | '/api/public/shipping/quote'
    | '/api/public/webhooks/razorpay'
    | '/api/public/webhooks/shiprocket'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/audit-logs'
    | '/admin/collections'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/import'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/'
    | '/admin/staff/$staffId'
    | '/admin/staff/permissions'
    | '/api/public/checkout'
    | '/api/public/collections'
    | '/api/public/products'
    | '/admin/staff/'
    | '/api/public/payments/verify'
    | '/api/public/products/$slug'
    | '/api/public/shipping/quote'
    | '/api/public/webhooks/razorpay'
    | '/api/public/webhooks/shiprocket'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicCheckoutRoute: typeof ApiPublicCheckoutRoute
  ApiPublicCollectionsRoute: typeof ApiPublicCollectionsRoute
  ApiPublicProductsRoute: typeof ApiPublicProductsRouteWithChildren
  ApiPublicPaymentsVerifyRoute: typeof ApiPublicPaymentsVerifyRoute
  ApiPublicShippingQuoteRoute: typeof ApiPublicShippingQuoteRoute
  ApiPublicWebhooksRazorpayRoute: typeof ApiPublicWebhooksRazorpayRoute
  ApiPublicWebhooksShiprocketRoute: typeof ApiPublicWebhooksShiprocketRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/collections': {
      id: '/admin/collections'
      path: '/collections'
      fullPath: '/admin/collections'
      preLoaderRoute: typeof AdminCollectionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/import': {
      id: '/admin/import'
      path: '/import'
      fullPath: '/admin/import'
      preLoaderRoute: typeof AdminImportRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/staff/': {
      id: '/admin/staff/'
      path: '/staff'
      fullPath: '/admin/staff/'
      preLoaderRoute: typeof AdminStaffIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/staff/$staffId': {
      id: '/admin/staff/$staffId'
      path: '/staff/$staffId'
      fullPath: '/admin/staff/$staffId'
      preLoaderRoute: typeof AdminStaffStaffIdRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/staff/permissions': {
      id: '/admin/staff/permissions'
      path: '/staff/permissions'
      fullPath: '/admin/staff/permissions'
      preLoaderRoute: typeof AdminStaffPermissionsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/api/public/checkout': {
      id: '/api/public/checkout'
      path: '/api/public/checkout'
      fullPath: '/api/public/checkout'
      preLoaderRoute: typeof ApiPublicCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/collections': {
      id: '/api/public/collections'
      path: '/api/public/collections'
      fullPath: '/api/public/collections'
      preLoaderRoute: typeof ApiPublicCollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/products': {
      id: '/api/public/products'
      path: '/api/public/products'
      fullPath: '/api/public/products'
      preLoaderRoute: typeof ApiPublicProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/verify': {
      id: '/api/public/payments/verify'
      path: '/api/public/payments/verify'
      fullPath: '/api/public/payments/verify'
      preLoaderRoute: typeof ApiPublicPaymentsVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/products/$slug': {
      id: '/api/public/products/$slug'
      path: '/$slug'
      fullPath: '/api/public/products/$slug'
      preLoaderRoute: typeof ApiPublicProductsSlugRouteImport
      parentRoute: typeof ApiPublicProductsRoute
    }
    '/api/public/shipping/quote': {
      id: '/api/public/shipping/quote'
      path: '/api/public/shipping/quote'
      fullPath: '/api/public/shipping/quote'
      preLoaderRoute: typeof ApiPublicShippingQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/razorpay': {
      id: '/api/public/webhooks/razorpay'
      path: '/api/public/webhooks/razorpay'
      fullPath: '/api/public/webhooks/razorpay'
      preLoaderRoute: typeof ApiPublicWebhooksRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/shiprocket': {
      id: '/api/public/webhooks/shiprocket'
      path: '/api/public/webhooks/shiprocket'
      fullPath: '/api/public/webhooks/shiprocket'
      preLoaderRoute: typeof ApiPublicWebhooksShiprocketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminCollectionsRoute: typeof AdminCollectionsRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminImportRoute: typeof AdminImportRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminStaffStaffIdRoute: typeof AdminStaffStaffIdRoute
  AdminStaffPermissionsRoute: typeof AdminStaffPermissionsRoute
  AdminStaffIndexRoute: typeof AdminStaffIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminCollectionsRoute: AdminCollectionsRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminImportRoute: AdminImportRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminStaffStaffIdRoute: AdminStaffStaffIdRoute,
  AdminStaffPermissionsRoute: AdminStaffPermissionsRoute,
  AdminStaffIndexRoute: AdminStaffIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface ApiPublicProductsRouteChildren {
  ApiPublicProductsSlugRoute: typeof ApiPublicProductsSlugRoute
}

const ApiPublicProductsRouteChildren: ApiPublicProductsRouteChildren = {
  ApiPublicProductsSlugRoute: ApiPublicProductsSlugRoute,
}

const ApiPublicProductsRouteWithChildren =
  ApiPublicProductsRoute._addFileChildren(ApiPublicProductsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicCheckoutRoute: ApiPublicCheckoutRoute,
  ApiPublicCollectionsRoute: ApiPublicCollectionsRoute,
  ApiPublicProductsRoute: ApiPublicProductsRouteWithChildren,
  ApiPublicPaymentsVerifyRoute: ApiPublicPaymentsVerifyRoute,
  ApiPublicShippingQuoteRoute: ApiPublicShippingQuoteRoute,
  ApiPublicWebhooksRazorpayRoute: ApiPublicWebhooksRazorpayRoute,
  ApiPublicWebhooksShiprocketRoute: ApiPublicWebhooksShiprocketRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
