/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicProductsRouteImport } from './routes/api/public/products'
import { Route as ApiPublicProductsSlugRouteImport } from './routes/api/public/products.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProductsRoute = ApiPublicProductsRouteImport.update({
  id: '/api/public/products',
  path: '/api/public/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProductsSlugRoute = ApiPublicProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ApiPublicProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/products': typeof ApiPublicProductsRouteWithChildren
  '/api/public/products/$slug': typeof ApiPublicProductsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/products': typeof ApiPublicProductsRouteWithChildren
  '/api/public/products/$slug': typeof ApiPublicProductsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/products': typeof ApiPublicProductsRouteWithChildren
  '/api/public/products/$slug': typeof ApiPublicProductsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/products' | '/api/public/products/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/products' | '/api/public/products/$slug'
  id: '__root__' | '/' | '/api/public/products' | '/api/public/products/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicProductsRoute: typeof ApiPublicProductsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/products': {
      id: '/api/public/products'
      path: '/api/public/products'
      fullPath: '/api/public/products'
      preLoaderRoute: typeof ApiPublicProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/products/$slug': {
      id: '/api/public/products/$slug'
      path: '/$slug'
      fullPath: '/api/public/products/$slug'
      preLoaderRoute: typeof ApiPublicProductsSlugRouteImport
      parentRoute: typeof ApiPublicProductsRoute
    }
  }
}

interface ApiPublicProductsRouteChildren {
  ApiPublicProductsSlugRoute: typeof ApiPublicProductsSlugRoute
}

const ApiPublicProductsRouteChildren: ApiPublicProductsRouteChildren = {
  ApiPublicProductsSlugRoute: ApiPublicProductsSlugRoute,
}

const ApiPublicProductsRouteWithChildren =
  ApiPublicProductsRoute._addFileChildren(ApiPublicProductsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicProductsRoute: ApiPublicProductsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
