ALTER TYPE public.app_role ADD VALUE IF NOT EXISTS 'MANAGER';
ALTER TYPE public.app_role ADD VALUE IF NOT EXISTS 'CATALOG_STAFF';
ALTER TYPE public.app_role ADD VALUE IF NOT EXISTS 'ORDER_STAFF';
ALTER TYPE public.app_role ADD VALUE IF NOT EXISTS 'MARKETING_STAFF';
ALTER TYPE public.app_role ADD VALUE IF NOT EXISTS 'SUPPORT';